### PR TITLE
attempt fix at co-pilot

### PR DESCRIPTION
**Pull request by choyiny**
Attempt fix at co-pilot

### CODE REVIEW

**Comment by FGDATA** [comment]
it seems we are still in experimental phase of restoring this code. I suggest not to merge with master branch yet, but instead create one or several branches for implementation and testing.
When we get it to work, we just merge into master

Notice my work on this branch:
https://github.com/FGMEMBERS/A320neo/tree/copilot-test
https://github.com/FGMEMBERS/A320neo/commit/9173d90b2cd3238327a0dfb604751b9f14e07955

IH-COL

**Comment by FGDATA** [comment]
I merged into another topic branch
https://github.com/FGMEMBERS/A320neo/tree/hkminegod-copilot-test

IH-COL

**Comment by choyiny** [comment]
Leaving pr open until i finish testing

**Comment by FGDATA** [comment]
yes... Please do

Also, test my solution I suggest above. It restored the content of XMLs directory that I think could help

Looking at your solution, seems also reasonable.

We need to test which one works

IH-cOL

**Comment by choyiny** [comment]
my changes goes 1 way only - co-pilot can detect pilot. Finished downloading, same with yours,

**Comment by IAHM-COL** [comment]
I Think that is how it used to work
The copilot used to select the pilot

I think that means yours is a fix (The simpler one)
we need testing with two ppl to see if the copilot can join in

IH-COL

**Comment by choyiny** [comment]
Pilot cannot select copilot, that is the problem

the pilot cannot "Select MP Copilot", as its not visible.

**Comment by choyiny** [comment]
Can you hop on mumble?

**Comment by IAHM-COL** [comment]
not today morning
but today afternoon, after the USA tour, definitely

**Comment by choyiny** [comment]
USA tour starts at 2am for me, so... not possible for me

**Comment by IAHM-COL** [comment]
If I remember correctly, Pilot did not select copilot. But copilot selected pilot.
Meaning that 's the only way it was coded before.

**Comment by IAHM-COL** [comment]
like 24h from now maybe? so Sunday morning UTC ?

**Comment by choyiny** [comment]
Negative. But co-pilot cannot interact with plane then?

**Comment by IAHM-COL** [comment]
yes. as I remember

**Comment by choyiny** [comment]
But tried, co-pilot can see no changes in aircraft except for the movement.

**Comment by choyiny** [comment]
It works now. Push to master :)

**Comment by IAHM-COL** [comment]
done
:)
Awesome

I will test tomorrow with some friend after USA tour then

**Comment by FGDATA** [comment]
looks really good .. Thanks for this one!

Now that youve joined you have push access to the collection. So you can finish merges yourself too ;P

IH-COL

**Pull request merged**
